version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/oidc-agent
    steps:
      - checkout
      - run: make build-linux
      - run: make build-darwin
      - run: make build-windows
