version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/oidc-agent
    parallelism: 4
    steps:
      - checkout
      - run: make build-linux
      - run: make build-darwin
      - run: make build-windows
      - store_artifacts:
          path: bin/
